### ISSUE TITLE
Where are the snippets?

### ISSUE THREAD

**Issue by mrroot5** [ayinloya/Materialize-Css-Atom-Snippets#1]
In your list you have losts of snippets but when I install the plugin I only have a few of them. For example I don't have de md-col:X. Look the screenshot below :-).

![where-is-the-snippets](https://cloud.githubusercontent.com/assets/1659540/24662179/445a7f66-194c-11e7-8886-d3eb6186bebf.png)

**Comment by ayinloya** [comment]
Oh I see, this was initially made for sublime but then ported to atom, I guess some of the snippets escaped me. I'll update the rest this weekend. Thanks for the reminder ;)

**Comment by mrroot5** [comment]
Thanks a lot for your support :-)

**Comment by mabdullah4** [comment]
Still waiting for update.. 👎

**Comment by ayinloya** [comment]
@mabdullah4 I've assigned this to someone, I'll keep you posted. Thanks

**Comment by ayinloya** [comment]
@erknrio @mabdullah4 A new version has been published. I'll be closing this issue. Feel free to reopen if you have any further issues, thanks

**Comment by sahalmhasa** [comment]
plugin doesn't work @ayinloya
