### ISSUE TITLE
Many Snippets not available.. 

### ISSUE THREAD

**Issue by mabdullah4** [ayinloya/Materialize-Css-Atom-Snippets#3]
Many ShortCut not working Like,
m-template:html
m-template:starter

navbar shortcut also not working..

![capture](https://cloud.githubusercontent.com/assets/18432746/26790862/b98f622a-4a2e-11e7-9084-91788afefcfb.JPG)

**Comment by ayinloya** [comment]
Thanks for bringing this to our notice, an update has been made
