### ISSUE TITLE
Getting Going

### ISSUE THREAD

**Issue by bretonio** [ayinloya/Materialize-Css-Atom-Snippets#4]
Probably a dumb question.

I have installed the Atom package. I have opened a new doc. I have activated the plugin with both <kbd>Ctrl-Alt-o</kbd> and selecting the item from the list at <kbd>Ctrl-Shift-P</kbd>.  

In both cases, a message in a modal reading `The MaterializeCss package is Alive! It's ALIVE!` and the message is not dismissible. And oddly you can continue to work on the file in the background, enter text and what not. 

But typing the key phrases and hitting <kbd>Tab</kbd> to expand the snippetpolymer has no effect.

Look forward to adopting your gizmo!

**Comment by ayinloya** [comment]
Hi @bretonio 
I will take a look at it, something must have changed. Thanks for the notice

**Comment by bretonio** [comment]
Thank you for swift reply! I do a lot with Materialize so your project is
like Christmas morning.

cb

**Comment by Alinnovatri** [comment]
Hi @ayinloya  
I have the same problem.

**Comment by ayinloya** [comment]
@bretonio @Alinnovatri  @erknrio It appears it has to do with atom itself, after installing some other packages I had to restart atom for it to work too. Does this issue still persist even now?

**Comment by Alinnovatri** [comment]
Solved, thank you @ayinloya .
