### ISSUE TITLE
what happened .pls help!

### ISSUE THREAD

**Issue by ananthunalloor** [ayinloya/Materialize-Css-Atom-Snippets#5]
Failed to load snippets from 'C:\Users\Ananthu.atom\packages\Materialize-Css\snippets\html.cson'
C:\Users\Ananthu\.atom\packages\Materialize-Css\snippets\html.cson: Duplicate key 'Materialize basic pagination'

**Comment by ayinloya** [comment]
I've seen the issue, 'Materialize basic pagination' has been repeated in the snippet
 I'll make an update to fix this

**Comment by baharalidurrani** [comment]
I change the 'Materialize basic pagination': to 'Materialize basic parallax': in the line number 1336 of C:\Users\Ananthu.atom\packages\Materialize-Css\snippets\html.cson file and it worked fine.

**Comment by sahalmhasa** [comment]
@baharalidurrani 

yes bro it's works. Thanks :+1:
